<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong>Poznámka:</strong> Pro správné zobrazení komentářů prosím použijte aktualizovaný prohlížeč.',
    'Download' => 'Stáhnout',
    'Follow' => 'Sledovat',
    'Fork' => 'Forknout',
    'Issue' => 'Issue',
    'Login with Facebook' => 'Přihlásit se pomocí Facebooku',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Pro správné zobrazení facebookového pluginu {pluginName} je potřeba mít v prohlížeči zapnutý JavaScript.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Pro správné zobrazení Google pluginu {pluginName} je potřeba mít v prohlížeči zapnutý JavaScript.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Pro správné zobrazení Twitter pluginu {pluginName} je potřeba mít v prohlížeči zapnutý JavaScript.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Pro správné zobrazení VKontakte pluginu {pluginName} je potřeba mít v prohlížeči zapnutý JavaScript.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Pro správné zobrazení {pluginLink} je potřeba mít zapnutý JavaScript.',
    'Star' => 'Přidat k oblíbeným',
    'Watch' => 'Sledovat',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Aby mohla stránka fungovat optimálně a zobrazovat kompletní sekce, je potřeba mít v prohlížeči zapnutý Javascript.',
    'comments powered by Disqus' => 'komentáře jsou zajištěny pomocí Disqus',
];
