<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login with Facebook' => '',
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong>Nota:</strong> Per favore usa un browser aggiornato per visualizzare i commenti.',
    'Download' => 'Download',
    'Follow' => 'Follow',
    'Fork' => 'Fork',
    'Issue' => 'Issue',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Per favore attiva JavaScript sul tuo browser per vedere correttamente il Facebook {pluginName} plugin su questo sito',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Per favore attiva JavaScript sul tuo browser per vedere correttamente il Google {pluginName} plugin su questo sito',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Per favore attiva JavaScript sul tuo browser per vedere correttamente il Twitter {pluginName} plugin su questo sito',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Per favore attiva JavaScript sul tuo browser per vedere correttamente il VKontakte {pluginName} plugin su questo sito',
    'Please enable JavaScript to view the {pluginLink}.' => 'Per favore attiva JavaScript per vedere il {pluginLink}.',
    'Star' => 'Star',
    'Watch' => 'Watch',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Devi attivare JavaScript sul tuo browser per visualizzare corettamente questo sito',
    'comments powered by Disqus' => 'commentato su Disqus',
];
