<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Вы должны включить Javascript в вашем браузере для оптимальной работы сайта и отображения разделов полностью.',
    'Please enable JavaScript to view the {pluginLink}' => 'Пожалуйста, включите JavaScript для просмотра {pluginLink}',
    'comments powered by Disqus' => 'комментарии простроенны на платформе Disqus',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Пожалуйста, включите JavaScript в вашем браузере, чтобы просмотреть Facebook {pluginName} и для его корректной работы на этом сайте.',
    'like' => 'нравиться',
    'share-button' => 'кнопка поделиться',
    'send' => 'отправить',
    'post' => 'пост',
    'follow' => 'следить',
    'comments' => 'комментарии',
    'activity' => 'активность',
    'recommendations' => 'рекомендации',
    'recommendations-bar' => 'раздел рекомендаций',
    'like-box' => 'раздел понравившегося',
    'facepile' => 'facepile'
);
