<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong>မွတ္ခ်က္။ </strong> ထင္ ျမင္ သံုးသပ္ခ်က္မ်ားကိုၾကည့္ရန္ ေနာက္ဆံုးေပၚ browser ကိုေက်းဇူးျပဳ၍ အသံုးျပဳပါ။',
    'Download' => 'ေဒါင္းလုပ္ရယူရန္',
    'Follow' => '',
    'Fork' => '',
    'Issue' => '',
    'Login with Facebook' => 'Facebook ျဖင့္၀င္ရန္',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Google {pluginName} plugin ကို ယခု၀က္ဆိုဘ္တြင္ မွန္ကန္စြာၾကည့္ရန္ JavaScript အား ေက်းဇူးျပဳ၍ သင္၏ browser တြင္  ဖြင့္ေပးပါ။',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Twitter {pluginName} plugin ကို ယခု၀က္ဆိုဘ္တြင္ မွန္ကန္စြာၾကည့္ရန္ JavaScript အား ေက်းဇူးျပဳ၍ သင္၏ browser တြင္ ဖြင့္ေပးပါ။',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'VKontakte {pluginName} plugin ကို ယခု၀က္ဆိုဘ္တြင္ မွန္ကန္စြာၾကည့္ရန္ JavaScript အား ေက်းဇူးျပဳ၍ သင္၏ browser တြင္ ဖြင့္ေပးပါ။',
    'Please enable JavaScript to view the {pluginLink}.' => '{pluginLink} အား ၾကည့္ရွဳရန္ ေက်းဇူးျပဳ၍ JavaScript အား ဖြင့္ေပးပါ။',
    'Star' => '',
    'Watch' => 'ၾကည့္မည္',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Facebook {pluginName} plugin ကို ယခု၀က္ဆိုဘ္တြင္ မွန္ကန္စြာၾကည့္ရန္ JavaScript အား ေက်းဇူးျပဳ၍ သင္၏ browser တြင္ ဖြင့္ေပးပါ။',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => '၀က္ဆိုဘ္ ေကာင္းမြန္စြာအလုပ္လုပ္ရန္ႏွင့္ ျပသမွဳအပိုင္းတြင္ျပီးျပည့္စံုေစရန္ ေက်းဇူးျပဳ၍ သင္၏ browser တြင္ JavaScript အား  ဖြင့္ေပးပါ။',
    'comments powered by Disqus' => 'Disqus မွ ထင္ ျမင္ သံုးသပ္ ခ်က္ မ်ားေရးသားႏိုင္ရန္ ျပဳလုပ္ေပးထားပါသည္။',
];