<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong>Let op:</strong> Gebruik alstublieft een bijgewerkte browser om opmerkingen te bekijken.',
    'Download' => 'Download',
    'Follow' => 'Volg',
    'Fork' => 'Vertakken',
    'Issue' => 'Probleem',
    'Login with Facebook' => 'Inloggen met Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Schakel alstublieft Javascript in op uw browser om de Facebook {pluginName} goed te kunnen bekijken.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Schakel alstublieft Javascript in op uw browser om de Google {pluginName} goed te kunnen bekijken.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Schakel alstublieft Javascript in op uw browser om de Twitter {pluginName} goed te kunnen bekijken.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Schakel alstublieft Javascript in op uw browser om de VKontakte {pluginName} goed te kunnen bekijken.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Schakel alstublieft Javascript in om de {pluginLink} te bekijken.',
    'Star' => 'Ster',
    'Watch' => 'Bekijk',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'U moet Javascript inschakelen op uw browser om deze site optimaal te gebruiken en alle secties correct te tonen.',
    'comments powered by Disqus' => 'commentaar aangedreven door Disqus',
];
