<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Sie müssen Javascript in Ihrem Browser aktivieren, damit die Seite optimal und Abschnitte komplett angezeigt wird.',
    'Please enable JavaScript to view the {pluginLink}' => 'Bitte aktivieren Sie Javascript um {pluginLink} zu sehen',
    'comments powered by Disqus' => 'Kommentare betrieben durch Disqus',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Bitte aktivieren Sie Javascript in Ihrem Browser um das Facebook {pluginName} plugin korrekt angezeigt zu bekommen',
    'like' => 'like',
    'share-button' => 'teilen',
    'send' => 'senden',
    'post' => 'Beitrag',
    'follow' => 'folgen',
    'comments' => 'Kommentare',
    'activity' => 'Aktivitäten',
    'recommendations' => 'Empfehlungen',
    'recommendations-bar' => 'Empfehlungsbar',
    'like-box' => 'like-box',
    'facepile' => 'facepile'
);
