<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Ви мусите дозволити Javascript у вашому браузері для оптимальної роботи сайта і відображення розділів повністю.',
    'Please enable JavaScript to view the {pluginLink}' => 'Будь ласка, увімкніть JavaScript для перегляду {pluginLink}',
    'comments powered by Disqus' => 'коментарі побудовані на платформі Disqus',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Будь ласка, увімкніть JavaScript у вашому браузері, щоб переглянути Facebook {pluginName} і для його коректної роботи на даному сайті.',
    'like' => 'подобається',
    'share-button' => 'кнопка поділитись',
    'send' => 'відправити',
    'post' => 'пост',
    'follow' => 'слідкувати',
    'comments' => 'коментарі',
    'activity' => 'активність',
    'recommendations' => 'рекомендації',
    'recommendations-bar' => 'розділ рекомендацій',
    'like-box' => 'розділ вподобань',
    'facepile' => 'facepile'
);
