<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Engedélyezned kell a JavaScipt-et a böngésződben, hogy az oldal optimálisan működjön és az oldal egyes részei teljesen látszódjanak.',
    'Please enable JavaScript to view the {pluginLink}' => 'Kérlek engedélyezd a JavaScipt-et, hogy megnézd a {pluginLink}-et',
    'comments powered by Disqus' => 'A hozzászólások a Disqus segítségével jöttek létre',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Kérlek engedélyezd a JavaScript-et a böngésződben, hogy jól jelenjen meg a Facebook {pluginName} plugin az oldalon.',
    'like' => 'tetszik',
    'share-button' => 'megosztás',
    'send' => 'küldés',
    'post' => 'küldés',
    'follow' => 'követés',
    'comments' => 'megjegyzések',
    'activity' => 'tevékenység',
    'recommendations' => 'ajánlások',
    'recommendations-bar' => 'ajánlások-sáv',
    'like-box' => 'like-box',
    'facepile' => 'facepile'
);
