<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Du skal aktivere Javascript i din browser for at siden kan virke optimalt og vise sektioner korrekt.',
    'Please enable JavaScript to view the {pluginLink}' => 'Aktiver venligst Javascript for at vise {pluginLink}',
    'comments powered by Disqus' => 'kommentarer drevet af Disqus',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Aktiver venligst Javascript i din browser for at vise Facebooks {pluginName} plugin korrekt på denne side.',
    'like' => 'synes-godt-om',
    'share-button' => 'del-knap',
    'send' => 'send',
    'post' => 'slå-op',
    'follow' => 'følg',
    'comments' => 'kommentarer',
    'activity' => 'aktivitet',
    'recommendations' => 'anbefalinger',
    'recommendations-bar' => 'anbefalinger-bar',
    'like-box' => 'synes-godt-om-boks',
    'facepile' => 'ansigtsstak'
);
